# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: reservation_development_db
test:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: reservation_test_db

production:
  <<: *default
  adapter: postgresql
  pool: 5
  encoding: utf8
  database: reservation_production_db

